version: '3.5'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:1.24.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./virtual-hosts/${NGINX_CONF_PATH}/:/etc/nginx/conf.d/
      - ./logs/:/var/log/nginx/
    networks:
      - net-nginx-proxy

networks:
  net-nginx-proxy:
    name: net-nginx-proxy
